apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache-deployment
  name: cache-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: redis
 template:
   metadata:
     labels:
       app: redis
   spec:
     containers:
     - name: redis
       image: redis:7.0.13
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1